# Generated by Django 3.2.8 on 2023-12-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_salida', models.TimeField(verbose_name='Hora de salida')),
                ('lugarInicio', models.CharField(max_length=30, verbose_name='Lugar inicio')),
                ('lugarDestino', models.CharField(max_length=30, verbose_name='Destino Viaje')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio')),
            ],
        ),
    ]
